{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mcpcounter
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "a79614e"

source:
  fn: mcpcounter_a79614e.tar.gz
  url:
    - https://github.com/ebecht/MCPcounter/archive/a79614eee002c88c64725d69140c7653e7c379b4.tar.gz
  sha256: cc2e842f629c0cc881ffc3273cd429528dd98241fc71de2e983b726db17255d1

  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, rmarkdown, shiny
requirements:
  build:
    - r-base =3.4.1
    - r-roxygen2 =6.0.1
    - r-curl =2.6
    - libcurl 7.60.0            # [osx]
    - curl 7.60.0            # [osx]
    - posix               # [win]
    - {{native}}toolchain # [win]
      #    - gcc                 # [not win]

  run:
    - r-base >=2.6.0
    - r-curl >=2.6
    - r-roxygen2 >=6.0.1

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('MCPcounter')" # [not win]
    - "\"%R%\" -e \"library('MCPcounter')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/ebecht/MCPcounter
  license: GPL-3
  summary: Estimating tissue-infiltrating immune and other stromal subpopulations abundances using gene expression
  license_family: GPL

# The original CRAN metadata for this package was:

# Package: MCPcounter
# Type: Package
# Title: Estimating tissue-infiltrating immune and other stromal subpopulations abundances using gene expression
# Version: 1.1.0
# Date: 2016-02-03
# Author: Etienne Becht, Aurelien de Reynies
# Maintainer: Etienne Becht <mcpcounter@gmail.com>
# Description: Estimating tissue-infiltrating immune and other stromal subpopulations abundances using gene expression
# License: GPL-3
# Depends: R (>= 2.6.0), curl
# LazyData: true
